# Generated by Django 2.2.4 on 2019-12-14 09:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import monitoring.submodels.paketModels
import monitoring.tools.pathAndRename


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_opd', models.CharField(default='OPD', max_length=255)),
                ('kepala_opd', models.CharField(default='Nama Kepala OPD', max_length=255)),
                ('alamat_opd', models.TextField(blank=True)),
                ('bendahara_opd', models.CharField(default='Nama Bendahara OPD', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(default='Paket Pekerjaan', max_length=255)),
                ('dana', models.CharField(choices=[('APBK', 'APBK'), ('DOKA', 'DOKA'), ('DAK', 'DAK'), ('TP', 'TP')], default='APBK', max_length=4)),
                ('pagu', models.PositiveIntegerField(default=0)),
                ('tahun_anggaran', models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1984), monitoring.submodels.paketModels.max_value_current_year])),
                ('hps', models.PositiveIntegerField(default=0)),
                ('metode_pengadaan', models.CharField(choices=[('SW', 'Swakelola'), ('TU', 'Tender'), ('EP', 'E-Katalog'), ('PL', 'Pengadaan Langsung'), ('TL', 'Penunjukan Langsung')], default='TU', max_length=2)),
                ('jenis_pengadaan', models.CharField(choices=[('BR', 'Barang'), ('JK', 'Jasa Konstruksi'), ('JS', 'Jasa Lainnya'), ('KS', 'Konsultansi')], default='JK', max_length=2)),
                ('nama_pptk', models.CharField(default='Nama PPTK', max_length=255)),
                ('hp_pptk', models.CharField(blank=True, default='Nomor HP PPTK', max_length=255)),
                ('persen_fisik', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('persen_keuangan', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nama_opd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Opd')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField(blank=True)),
                ('foto1', models.ImageField(default='-', upload_to=monitoring.tools.pathAndRename.PathAndRename('dokumentasi/'))),
                ('foto2', models.ImageField(default='-', upload_to=monitoring.tools.pathAndRename.PathAndRename('dokumentasi/'))),
                ('foto3', models.ImageField(default='-', upload_to=monitoring.tools.pathAndRename.PathAndRename('dokumentasi/'))),
                ('foto4', models.ImageField(default='-', upload_to=monitoring.tools.pathAndRename.PathAndRename('dokumentasi/'))),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('tanggal_monitoring', models.DateField()),
                ('persen_fisik', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('persen_keuangan', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tampil', models.BooleanField(default=True)),
                ('prioritas', models.PositiveSmallIntegerField(default=99)),
                ('nama_pptk', models.CharField(default='Nama PPTK', max_length=255)),
                ('nama_paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Paket')),
            ],
        ),
    ]
